##
    # Wordpress
    #


    #- name: Clone wordpress
    #  subversion: repo=http://core.svn.wordpress.org/tags/$wordpress_version dest=/var/www/wordpress
    #  tags: wordpress
    #  register: gitclonewordpressresult
    #  ignore_errors: True
    #  notify: 
    #  - restart apache2

    - name: write fact to file
      template: src=ec2_mysql.txt.j2 dest=/tmp/ec2_mysql.txt

    - set_fact: other_fact="{{ groups['tag_Group_MySQL'][0] }}"
