---
- name: Provision EC2 images
  hosts:
    - control

  roles:
    - ec2_prov

- name: Install Wordpress
  hosts: 
    - tag_Group_Wordpress
  user: "{{ remote_user }}"
  sudo: yes

  roles:
    - wordpress