---
- name: Install common config on all nodes
  hosts: all
  user: root

  tasks:
  - name: ensure apt cache is up to date (hardcoded task)
    action: apt update_cache=yes

  roles:
    - common
#  handlers:
#    - include: handlers/handlers.yml

- name: Install control node stuff on control node(s)
  hosts: control
  user: root

  roles:
    - controlnode
    - dumpvars

- name: Install mysql apache wordpress on wordpress node(s)
  hosts: wordpress
  user: root

  roles:
    - mysql
    - apache2
    - wordpress
    - wordpress_sitetest
    - dumpvars
  handlers:
    - include: handlers/handlers.yml



