---
- name: Install common config on all nodes
  hosts: all
  user: root

  roles:
    - common

- name: Install control node stuff on control node(s)
  hosts: control
  user: root

  roles:
    - controlnode

- name: Install mysql, apache, wordpress on worpress node(s)
  hosts: wordpress
  user: root

  roles:
    - mysql
    - apache2





#- name: Install Wordpress, MySQL, Nginx, and PHP-FPM
#  hosts: njetwordpress-server
#  user: root

#  roles:
#    - common
#    - mysql 
#    - nginx
#    - php-fpm
#    - wordpress
