---
- name: Install common config on all nodes
  hosts: all
  user: root

  roles:
    - common
  handlers:
#    - include: handlers/handlers.yml

- name: Install control node stuff on control node(s)
  hosts: control
  user: root

  roles:
    - controlnode
    - dumpvars

- name: Install mysql apache wordpress on wordpress node(s)
  hosts: wordpress
  user: root

  roles:
    - mysql
    - apache2
    - wordpress
    - dumpvars



