---
- name: Install control stuff on control node
  hosts: control
  user: root

  roles:
    - common
    - controlnode

#- name: Install Wordpress, MySQL, Nginx, and PHP-FPM
#  hosts: njetwordpress-server
#  user: root

#  roles:
#    - common
#    - mysql 
#    - nginx
#    - php-fpm
#    - wordpress
