---
- name: Install common config on all nodes
  hosts: all
  user: root

  roles:
    - common

- name: Install control node stuff on control node(s)
  hosts: control
  user: root

  roles:
    - control




#- name: Install Wordpress, MySQL, Nginx, and PHP-FPM
#  hosts: njetwordpress-server
#  user: root

#  roles:
#    - common
#    - mysql 
#    - nginx
#    - php-fpm
#    - wordpress
