---
- name: Install common config on all nodes
  hosts: all
  user: root

  roles:
    - common

- name: Install control node stuff on control node(s)
  hosts: control
  user: root

  roles:
    - controlnode
    - dumpvars

- name: Install mysql apache wordpress on wordpress node(s)
  hosts: wordpress
  user: root

  roles:
    - mysql
    - apache2
    - wordpress
    - wordpress_sitetest
    - dumpvars
  handlers:
    - include: handlers/handlers.yml

# - name: Install jenkins
#   hosts: jenkins
#   user: root

#   roles:
#     - jenkins




