    - name: copy powershell file
      action: template src=wordpressinstaller.ps1.j2 dest="/opt/tclwinrunner/wordpressinstaller.ps1"
      tags: wordpress_windows

    - name: Connect to node and run script
      action: winrm pshostname="192.168.188.155" psscriptname="/opt/tclwinrunner/wordpressinstaller.ps1" psusername="administrator" pspassword="MyPassword123"
      tags: wordpress_windows