---
- name: Install common config on all nodes
  hosts: 
    - tag_Group_Wordpress
    - tag_Group_MySQL
  user: {{ remote_user }}
  sudo: yes
  serial: 9999

  roles:
    - common

- name: Install MySQL
  hosts: 
    - tag_Group_MySQL
  user: ubuntu
  sudo: yes

  roles:
    - mysql

- name: Install Wordpress
  hosts: 
    - tag_Group_Wordpress
  user: ubuntu
  sudo: yes

  roles:
    - apache2
    - wordpress