##
# Ansible playbook for setting up a LAMP development server on Ubuntu 12.04.
#

---
- hosts: carmudgeons
  sudo: yes
  vars:
    server_hostname: 'carmudgeons.com'
    apache_server_alias: '*.carmudgeons.com'
    s3_backup_folder: digitalocean-carmudgeons

  vars_files:
    - vars/default-settings.yml
    - vars/private-settings.yml

  tasks:
    - name: Update APT package cache
      action: apt update_cache=yes
      tags: common

    - name: Run apt-get upgrade
      action: apt upgrade=dist
      tags: common

    - name: Install fail2ban
      action: apt pkg=fail2ban state=installed
      tags: common

    - name: zsh
      action: apt pkg=zsh state=installed
      tags: common

    - name: Add ayn user
      action: user name=ayn password=$ayn_password shell=/usr/bin/zsh
      tags: common

    - name: Add authorized key for ayn
      action: authorized_key user=ayn key='$FILE(files/ayn.pub)'
      tags: common

    - name: Remove sudo group rights
      action: lineinfile dest=/etc/sudoers regexp="^%sudo" state=absent
      tags: common

    - name: Add ayn user to sudoers
      action: lineinfile dest=/etc/sudoers regexp="ayn ALL" line="ayn ALL=(ALL) ALL" state=present
      tags: common

    - name: Disallow root SSH access
      action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
      tags: ssh
      notify: Restart sshd

    - name: Disallow password authentication
      action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
      tags: common
      notify: Restart sshd

    - name: Install unattended-upgrades
      action: apt pkg=unattended-upgrades state=present
      tags: common

    - name: Adjust APT update intervals
      action: copy src=files/apt_periodic dest=/etc/apt/apt.conf.d/10periodic
      tags: common

    - name: Make sure unattended-upgrades only installs from $ubuntu_release-security
      action: lineinfile dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent
      tags: common

    - name: Copy debconf selections so that Postfix can configure itself non-interactively
      copy: src=files/postfix_selections  dest=/tmp/postfix_selections
      tags: common

    - name: Set up Postfix to relay mail
      action: command debconf-set-selections /tmp/postfix_selections
      tags: common

    - name: Install logwatch
      action: apt pkg=logwatch state=installed
      tags: common

    - name: Make logwatch mail $logwatch_email daily
      action: lineinfile dest=/etc/cron.daily/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch --output mail --mailto $logwatch_email --detail high" state=present create=yes
      tags: common

    - name: Install python-software-properties
      apt: pkg=python-software-properties state=installed
      tags: update_mosh_repo

    - name: Install latest mosh
      apt_repository: repo=ppa:keithw/mosh
      tags: update_mosh_repo

    ##
    # Apt package installation of required software.
    #
    - name: General | Install required packages.
      action: apt pkg=$item state=installed
      tags: ayn
      with_items:
        - php5
        - apache2
        - mysql-server
        - mysql-client
        - php5-mysql
        - php-apc
        - php5-xmlrpc
        - php-soap
        - php5-gd
        - php5-memcache
        - php5-memcached
        - unzip
        - python-mysqldb
        - git
        - screen
        - memcached
        - strace
        - atsar
        - uptimed
        - mosh

    - name: my dotfiles, will have to rake install later
      git: repo=git://github.com/ayn/dotfiles.git dest=~ayn/.dotfiles

    - name: chown dotfiles
      file: path=~ayn/.dotfiles recurse=yes owner=ayn group=ayn state=directory

    ##
    # Message of the day explaining server is under control of Ansible.
    #
    - name: General | Message of the day explaining server is under Ansible control.
      action: copy src=files/etc-update-motd-d-95-ansible dest=/etc/update-motd.d/95-ansible mode=755
      tags: common

    ##
    # PHP Setup.
    #
    - name: PHP | Configuration file, php.ini
      action: template src=templates/etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini
      tags: common

    - name: APC | Cache configuration file, apc.ini
      action: template src=templates/etc-php5-conf-d-apc-ini.j2 dest=/etc/php5/conf.d/apc.ini
      tags: common

    ##
    # MySQL database setup.
    #
    - name: MySQL | Configuration file, my.cnf
      action: template src=templates/etc-mysql-my-cnf.j2 dest=/etc/mysql/my.cnf
      tags: common

    - include: common-tasks/mysql-secure.yml

    - include: common-tasks/s3-backup.yml

    ##
    # Apache2 setup.
    #
    - name: Apache | Enable some required modules
      action: command a2enmod rewrite vhost_alias
      tags: common

    - name: Apache | Configuration file for our site
      action: template src=templates/etc-apache2-sites-available-carmudgeons.j2 dest=/etc/apache2/sites-available/carmudgeons
      tags: common

    - name: Apache | Disable the default site
      action: command a2dissite default
      tags: common

    - name: Apache | Enable our new site
      action: command a2ensite carmudgeons
      tags: common

    - name: Restart Apache
      action: service name=apache2 state=restarted
      tags: common

    - name: Restart MySQL
      action: service name=mysql state=restarted
      tags: common

  ##
  # Restart services
  #
  handlers:
    - name: Restart sshd
      action: service name=ssh state=restarted
      tags: common

