---
- hosts: webservers
  remote_user: root
  tasks:
  - name: install apache2
    apt: name=apache2 state=latest
  - name: install git
    apt: name=git state=latest
  - name: clone git repo
    git: repo=git://github.com/trondhindenes/AnsibleTest.git dest=/home/checkout/AnsibleTest
  - name: copy index file
    copy: src=/home/checkout/AnsibleTest/WebServerContent/index.html dest=/var/www/index.html


