---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    apt: pkg=apache2 state=latest  
    notify:
    - restart apache
  - name: ensure apache is running
    service: name=apache2 state=started
- git: repo=git://github.com/trondhindenes/AnsibleTest.git
       dest=/home/checkout/AnsibleTest
	
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted